//    Proprietary Program Material
//    This material is proprietary to Lawson Software, and is not to be
//    reproduced or disclosed except in accordance with software contract
//    provisions, or upon written authorization from Lawson Software.
//
//    Copyright (C) 2001-2007 by Lawson Software. All Rights Reserved.
//    Saint Paul, Minnesota
//What String:@(#)$Header: /cvs/cvs_archive/LawsonPlatform/ui/info_office/javascript/colormap.js,v 1.1.26.1 2007/02/06 22:08:32 keno Exp $ $Name: REVIEWED_901 $ 
// Description: This function returns a tet string of a image map in a table form to select 
//              colors.  The process will allow mouse overs and clicks.
// Arguments:   The name of the table so you can have multiple per frame, a unique identifier.
//              You will need in your program three
//              functions that will do what you want in the case of a click, mouse
//              over, or mouse out.  Those three functions are called
//              colorClick(), colorOver(), and colorOut().         

function colorMap(tableName,camefrom)
{
var temp = "<script>var camefrom=" + camefrom + "</scr" + "ipt><table border=1 cellpadding=0 cellspacing=0>"
			+ "<tr>"
			+ "<td bgcolor=#e0e0e0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','e0e0e0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d50000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d50000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d54700> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d54700')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d58e00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d58e00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d5d500> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d5d500')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#8ed500> <a href=\"javascript:camefrom.colorClick('" + tableName + "','8ed500')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#47d500> <a href=\"javascript:camefrom.colorClick('" + tableName + "','47d500')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00d500> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00d500')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00d547> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00d547')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00d58e> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00d58e')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00d5d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00d5d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#008ed5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','008ed5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0047d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0047d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0000d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0000d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#4700d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','4700d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#8e00d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','8e00d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d500d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d500d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d5008e> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d5008e')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d50047> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d50047')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d59393> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d59393')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d5a993> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d5a993')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d5be93> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d5be93')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d5d593> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d5d593')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#bed593> <a href=\"javascript:camefrom.colorClick('" + tableName + "','bed593')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#a9d593> <a href=\"javascript:camefrom.colorClick('" + tableName + "','a9d593')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#93d593> <a href=\"javascript:camefrom.colorClick('" + tableName + "','93d593')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#93d5a9> <a href=\"javascript:camefrom.colorClick('" + tableName + "','93d5a9')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#93d5be> <a href=\"javascript:camefrom.colorClick('" + tableName + "','93d5be')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#93d5d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','93d5d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#93bed5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','93bed5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#93a9d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','93a9d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#9393d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','9393d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#a993d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','a993d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#be93d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','be93d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d593d5> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d593d5')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d593be> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d593be')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#d593a9> <a href=\"javascript:camefrom.colorClick('" + tableName + "','d593a9')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "</tr><tr>"
			+ "<td bgcolor=#ffffff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffffff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ff0000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ff0000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ff5500> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ff5500')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffaa00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffaa00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffff00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffff00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aaff00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aaff00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#55ff00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','55ff00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00ff00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00ff00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00ff55> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00ff55')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00ffaa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00ffaa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00ffff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00ffff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00aaff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00aaff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0000ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0000ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0000ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0000ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#5500ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','5500ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa00ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa00ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ff00ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ff00ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ff00aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ff00aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ff0055> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ff0055')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffb0b0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffb0b0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffcab0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffcab0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffe4b0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffe4b0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffffb0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffffb0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#e4ffb0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','e4ffb0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#caffb0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','caffb0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0ffb0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0ffb0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0ffca> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0ffca')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0ffe4> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0ffe4')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0ffff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0ffff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0e4ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0e4ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0caff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0caff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#b0b0ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','b0b0ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#cab0ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','cab0ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#e4b0ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','e4b0ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffb0ff> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffb0ff')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffb0e4> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffb0e4')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#ffb0ca> <a href=\"javascript:camefrom.colorClick('" + tableName + "','ffb0ca')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			
			+ "</tr><tr>"
			+ "<td bgcolor=#c0c0c0> <a href=\"javascript:camefrom.colorClick('" + tableName + "','c0c0c0')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa0000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa0000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa3900> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa3900')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa7200> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa7200')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aaaa00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aaaa00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#72aa00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','72aa00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#39aa00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','39aa00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00aa00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00aa00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00aa39> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00aa39')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00aa72> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00aa72')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00aaaa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00aaaa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0072aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0072aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0039aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0039aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#0000aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','0000aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#3900aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','3900aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#7200aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','7200aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa00aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa00aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa0072> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa0072')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa0039> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa0039')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa7676> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa7676')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa8776> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa8776')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa9876> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa9876')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aaaa76> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aaaa76')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#98aa76> <a href=\"javascript:camefrom.colorClick('" + tableName + "','98aa76')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#87aa76> <a href=\"javascript:camefrom.colorClick('" + tableName + "','87aa76')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#76aa76> <a href=\"javascript:camefrom.colorClick('" + tableName + "','76aa76')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#76aa87> <a href=\"javascript:camefrom.colorClick('" + tableName + "','76aa87')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#76aa98> <a href=\"javascript:camefrom.colorClick('" + tableName + "','76aa98')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#76aaaa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','76aaaa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#7698aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','7698aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#7687aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','7687aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#7676aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','7676aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#8776aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','8776aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#9876aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','9876aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa76aa> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa76aa')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa7698> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa7698')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#aa7687> <a href=\"javascript:camefrom.colorClick('" + tableName + "','aa7687')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			
			+ "</tr><tr>"
			+ "<td bgcolor=#808080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','808080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#800000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','800000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#802b00> <a href=\"javascript:camefrom.colorClick('" + tableName + "','802b00')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#805500> <a href=\"javascript:camefrom.colorClick('" + tableName + "','805500')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#808000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','808000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#558000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','558000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#2b8000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','2b8000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#008000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','008000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#00802b> <a href=\"javascript:camefrom.colorClick('" + tableName + "','00802b')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#008055> <a href=\"javascript:camefrom.colorClick('" + tableName + "','008055')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#008080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','008080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#005580> <a href=\"javascript:camefrom.colorClick('" + tableName + "','005580')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#002b80> <a href=\"javascript:camefrom.colorClick('" + tableName + "','002b80')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#000080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','000080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#2b0080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','2b0080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#550080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','550080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#800080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','800080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#800055> <a href=\"javascript:camefrom.colorClick('" + tableName + "','800055')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#80002b> <a href=\"javascript:camefrom.colorClick('" + tableName + "','80002b')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#805858> <a href=\"javascript:camefrom.colorClick('" + tableName + "','805858')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#806558> <a href=\"javascript:camefrom.colorClick('" + tableName + "','806558')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#807258> <a href=\"javascript:camefrom.colorClick('" + tableName + "','807258')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#808058> <a href=\"javascript:camefrom.colorClick('" + tableName + "','808058')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#728058> <a href=\"javascript:camefrom.colorClick('" + tableName + "','728058')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#658058> <a href=\"javascript:camefrom.colorClick('" + tableName + "','658058')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#588058> <a href=\"javascript:camefrom.colorClick('" + tableName + "','588058')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#588065> <a href=\"javascript:camefrom.colorClick('" + tableName + "','588065')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#588072> <a href=\"javascript:camefrom.colorClick('" + tableName + "','588072')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#588080> <a href=\"javascript:camefrom.colorClick('" + tableName + "','588080')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#587280> <a href=\"javascript:camefrom.colorClick('" + tableName + "','587280')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#586580> <a href=\"javascript:camefrom.colorClick('" + tableName + "','586580')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#585880> <a href=\"javascript:camefrom.colorClick('" + tableName + "','585880')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#655880> <a href=\"javascript:camefrom.colorClick('" + tableName + "','655880')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#725880> <a href=\"javascript:camefrom.colorClick('" + tableName + "','725880')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#805880> <a href=\"javascript:camefrom.colorClick('" + tableName + "','805880')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#805872> <a href=\"javascript:camefrom.colorClick('" + tableName + "','805872')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			+ "<td bgcolor=#000000> <a href=\"javascript:camefrom.colorClick('" + tableName + "','000000')\"> <img src=/lawson/images/misc/trans.gif height=10 width=10 border=0></a></td>" 
			
			+ "</tr><tr>"
		
			+ "</table>"
return(temp)
}
